In [28]:
import sys
print(sys.executable)

c:\Users\achur\desktop\AISE_CLASS_CLONES\march-madness-bracket-simulator\.venv\Scripts\python.exe

In [29]:
import pandas as pd
import numpy as np
import sklearn

print(pd.__version__)
print(np.__version__)
print(sklearn.__version__)

2.3.3
2.4.3
1.8.0

In [30]:
from pathlib import Path

data_dir = Path("../data/raw")
sorted([p.name for p in data_dir.glob("*.csv")])[:20]

['Cities.csv',
 'Conferences.csv',
 'MConferenceTourneyGames.csv',
 'MGameCities.csv',
 'MMasseyOrdinals.csv',
 'MNCAATourneyCompactResults.csv',
 'MNCAATourneyDetailedResults.csv',
 'MNCAATourneySeedRoundSlots.csv',
 'MNCAATourneySeeds.csv',
 'MNCAATourneySlots.csv',
 'MRegularSeasonCompactResults.csv',
 'MRegularSeasonDetailedResults.csv',
 'MSeasons.csv',
 'MSecondaryTourneyCompactResults.csv',
 'MSecondaryTourneyTeams.csv',
 'MTeamCoaches.csv',
 'MTeamConferences.csv',
 'MTeamSpellings.csv',
 'MTeams.csv',
 'SampleSubmissionStage1.csv']

## Load Core Men's NCAA Datasets

This cell loads the main datasets needed for the project:
- teams
- regular season results
- tournament results
- seeds
- bracket slots

In [31]:
import pandas as pd
from pathlib import Path

data_dir = Path("../data/raw")

m_teams = pd.read_csv(data_dir / "MTeams.csv")
m_reg = pd.read_csv(data_dir / "MRegularSeasonCompactResults.csv")
m_tourney = pd.read_csv(data_dir / "MNCAATourneyCompactResults.csv")
m_seeds = pd.read_csv(data_dir / "MNCAATourneySeeds.csv")
m_slots = pd.read_csv(data_dir / "MNCAATourneySlots.csv")

In [32]:
datasets = {
    "teams": m_teams,
    "regular_season": m_reg,
    "tourney": m_tourney,
    "seeds": m_seeds,
    "slots": m_slots,
}

for name, df in datasets.items():
    print(f"--- {name} ---")
    print("shape:", df.shape)
    print("columns:", df.columns.tolist())
    display(df.head())

--- teams ---
shape: (381, 4)
columns: ['TeamID', 'TeamName', 'FirstD1Season', 'LastD1Season']

   TeamID     TeamName  FirstD1Season  LastD1Season
0    1101  Abilene Chr           2014          2026
1    1102    Air Force           1985          2026
2    1103        Akron           1985          2026
3    1104      Alabama           1985          2026
4    1105  Alabama A&M           2000          2026

--- regular_season ---
shape: (198079, 8)
columns: ['Season', 'DayNum', 'WTeamID', 'WScore', 'LTeamID', 'LScore', 'WLoc', 'NumOT']

   Season  DayNum  WTeamID  WScore  LTeamID  LScore WLoc  NumOT
0    1985      20     1228      81     1328      64    N      0
1    1985      25     1106      77     1354      70    H      0
2    1985      25     1112      63     1223      56    H      0
3    1985      25     1165      70     1432      54    H      0
4    1985      25     1192      86     1447      74    H      0

--- tourney ---
shape: (2585, 8)
columns: ['Season', 'DayNum', 'WTeamID', 'WScore', 'LTeamID', 'LScore', 'WLoc', 'NumOT']

   Season  DayNum  WTeamID  WScore  LTeamID  LScore WLoc  NumOT
0    1985     136     1116      63     1234      54    N      0
1    1985     136     1120      59     1345      58    N      0
2    1985     136     1207      68     1250      43    N      0
3    1985     136     1229      58     1425      55    N      0
4    1985     136     1242      49     1325      38    N      0

--- seeds ---
shape: (2626, 3)
columns: ['Season', 'Seed', 'TeamID']

   Season Seed  TeamID
0    1985  W01    1207
1    1985  W02    1210
2    1985  W03    1228
3    1985  W04    1260
4    1985  W05    1374

--- slots ---
shape: (2586, 4)
columns: ['Season', 'Slot', 'StrongSeed', 'WeakSeed']

   Season  Slot StrongSeed WeakSeed
0    1985  R1W1        W01      W16
1    1985  R1W2        W02      W15
2    1985  R1W3        W03      W14
3    1985  R1W4        W04      W13
4    1985  R1W5        W05      W12

In [33]:
m_slots.head(15)

    Season  Slot StrongSeed WeakSeed
0     1985  R1W1        W01      W16
1     1985  R1W2        W02      W15
2     1985  R1W3        W03      W14
3     1985  R1W4        W04      W13
4     1985  R1W5        W05      W12
5     1985  R1W6        W06      W11
6     1985  R1W7        W07      W10
7     1985  R1W8        W08      W09
8     1985  R1X1        X01      X16
9     1985  R1X2        X02      X15
10    1985  R1X3        X03      X14
11    1985  R1X4        X04      X13
12    1985  R1X5        X05      X12
13    1985  R1X6        X06      X11
14    1985  R1X7        X07      X10

In [34]:
m_slots["Season"].min(), m_slots["Season"].max()

(np.int64(1985), np.int64(2025))

In [35]:
m_slots[m_slots["Season"] == m_slots["Season"].max()].head(20)

      Season  Slot StrongSeed WeakSeed
2519    2025  R1W1        W01      W16
2520    2025  R1W2        W02      W15
2521    2025  R1W3        W03      W14
2522    2025  R1W4        W04      W13
2523    2025  R1W5        W05      W12
2524    2025  R1W6        W06      W11
2525    2025  R1W7        W07      W10
2526    2025  R1W8        W08      W09
2527    2025  R1X1        X01      X16
2528    2025  R1X2        X02      X15
2529    2025  R1X3        X03      X14
2530    2025  R1X4        X04      X13
2531    2025  R1X5        X05      X12
2532    2025  R1X6        X06      X11
2533    2025  R1X7        X07      X10
2534    2025  R1X8        X08      X09
2535    2025  R1Y1        Y01      Y16
2536    2025  R1Y2        Y02      Y15
2537    2025  R1Y3        Y03      Y14
2538    2025  R1Y4        Y04      Y13

In [36]:
m_slots[m_slots["Season"] == 1985].tail(20)

    Season  Slot StrongSeed WeakSeed
43    1985  R2Y4       R1Y4     R1Y5
44    1985  R2Z1       R1Z1     R1Z8
45    1985  R2Z2       R1Z2     R1Z7
46    1985  R2Z3       R1Z3     R1Z6
47    1985  R2Z4       R1Z4     R1Z5
48    1985  R3W1       R2W1     R2W4
49    1985  R3W2       R2W2     R2W3
50    1985  R3X1       R2X1     R2X4
51    1985  R3X2       R2X2     R2X3
52    1985  R3Y1       R2Y1     R2Y4
53    1985  R3Y2       R2Y2     R2Y3
54    1985  R3Z1       R2Z1     R2Z4
55    1985  R3Z2       R2Z2     R2Z3
56    1985  R4W1       R3W1     R3W2
57    1985  R4X1       R3X1     R3X2
58    1985  R4Y1       R3Y1     R3Y2
59    1985  R4Z1       R3Z1     R3Z2
60    1985  R5WX       R4W1     R4X1
61    1985  R5YZ       R4Y1     R4Z1
62    1985  R6CH       R5WX     R5YZ

In [37]:
from march_madness_bracket_simulator.data_loader import load_core_march_madness_data

data = load_core_march_madness_data()

for name, df in data.items():
    print(name, df.shape)

teams (381, 4)
regular_season (198079, 8)
tourney (2585, 8)
seeds (2626, 3)
slots (2586, 4)

In [38]:
from march_madness_bracket_simulator.feature_engineering import build_team_season_features

team_features = build_team_season_features(data["regular_season"])
team_features.head()

,Season,TeamID,wins,losses,games,win_pct,avg_points_for,avg_points_against,avg_scoring_margin
0,1985,1102,5.0,19.0,24.0,0.208333,63.083333,68.875000,-5.791667
1,1985,1103,9.0,14.0,23.0,0.391304,61.043478,64.086957,-3.043478
2,1985,1104,21.0,9.0,30.0,0.700000,68.500000,60.700000,7.800000
3,1985,1106,10.0,14.0,24.0,0.416667,71.625000,75.416667,-3.791667
4,1985,1108,19.0,6.0,25.0,0.760000,83.000000,75.040000,7.960000

In [39]:
team_features_named = team_features.merge(
    data["teams"][["TeamID", "TeamName"]],
    on="TeamID",
    how="left"
)

team_features_named = team_features_named.merge(
    data["seeds"],
    on=["Season", "TeamID"],
    how="left"
)

team_features_named.head()

,Season,TeamID,wins,losses,games,win_pct,avg_points_for,avg_points_against,avg_scoring_margin,TeamName,Seed
0,1985,1102,5.0,19.0,24.0,0.208333,63.083333,68.875000,-5.791667,Air Force,NaN
1,1985,1103,9.0,14.0,23.0,0.391304,61.043478,64.086957,-3.043478,Akron,NaN
2,1985,1104,21.0,9.0,30.0,0.700000,68.500000,60.700000,7.800000,Alabama,X07
3,1985,1106,10.0,14.0,24.0,0.416667,71.625000,75.416667,-3.791667,Alabama St,NaN
4,1985,1108,19.0,6.0,25.0,0.760000,83.000000,75.040000,7.960000,Alcorn St,NaN

In [40]:
team_features_named[team_features_named["Season"] == 1985].sort_values(
    "avg_scoring_margin", ascending=False
).head(15)

,Season,TeamID,wins,losses,games,win_pct,avg_points_for,avg_points_against,avg_scoring_margin,TeamName,Seed
80,1985,1207,25.0,2.0,27.0,0.925926,75.740741,60.074074,15.666667,Georgetown,W01
174,1985,1328,25.0,5.0,30.0,0.833333,89.833333,76.533333,13.300000,Oklahoma,Y01
118,1985,1256,26.0,2.0,28.0,0.928571,77.500000,64.821429,12.678571,Louisiana Tech,Y05
261,1985,1439,19.0,8.0,27.0,0.703704,81.148148,69.185185,11.962963,Virginia Tech,W09
217,1985,1385,27.0,3.0,30.0,0.900000,76.133333,64.400000,11.733333,St John's,X01
60,1985,1181,22.0,7.0,29.0,0.758621,79.241379,67.896552,11.344828,Duke,Y03
152,1985,1298,23.0,5.0,28.0,0.821429,78.214286,67.321429,10.892857,Navy,Z13
98,1985,1228,23.0,8.0,31.0,0.741935,68.225806,57.354839,10.870968,Illinois,W03
136,1985,1276,25.0,3.0,28.0,0.892857,79.750000,69.107143,10.642857,Michigan,Z01
103,1985,1234,20.0,10.0,30.0,0.666667,69.733333,59.266667,10.466667,Iowa,X08
133,1985,1272,26.0,3.0,29.0,0.896552,75.137931,64.689655,10.448276,Memphis,Y02
247,1985,1424,27.0,3.0,30.0,0.900000,82.666667,72.566667,10.100000,UNLV,X04
255,1985,1433,25.0,5.0,30.0,0.833333,72.433333,62.566667,9.866667,VCU,X02
81,1985,1208,19.0,8.0,27.0,0.703704,77.592593,68.185185,9.407407,Georgia,W06
83,1985,1210,24.0,7.0,31.0,0.774194,70.903226,61.548387,9.354839,Georgia Tech,W02